import { NAMESPACES, expandCurie } from './namespaces';
import type { KnownPrefix } from './namespaces';

/**
 * How an annotation's value is written into RDF.
 *  - `text`     plain literal, may carry a language tag (rdfs:label, skos:definition, ...)
 *  - `iri`      the value is an IRI reference (dcterms:creator as a URI, prov:wasDerivedFrom)
 *  - `date`     xsd:date typed literal (dcterms:created)
 *  - `plain`    literal that must never carry a language tag (owl:versionInfo)
 */
export type AnnotationValueKind = 'text' | 'iri' | 'date' | 'plain';

export interface AnnotationTerm {
  /** CURIE, e.g. `skos:prefLabel`. Doubles as the term's stable id in the model. */
  readonly curie: string;
  readonly prefix: KnownPrefix;
  readonly label: string;
  readonly kind: AnnotationValueKind;
  readonly hint: string;
}

const term = (
  curie: string,
  label: string,
  kind: AnnotationValueKind,
  hint: string,
): AnnotationTerm => ({
  curie,
  prefix: curie.slice(0, curie.indexOf(':')) as KnownPrefix,
  label,
  kind,
  hint,
});

/**
 * The annotation vocabulary offered throughout the app: RDFS, OWL, Dublin Core Terms,
 * SKOS and PROV-O. Ordered for presentation; grouped by prefix in the UI.
 */
export const ANNOTATION_TERMS: readonly AnnotationTerm[] = [
  term('rdfs:label', 'Label', 'text', 'Human-readable name'),
  term('rdfs:comment', 'Comment', 'text', 'Free-text description'),
  term('rdfs:seeAlso', 'See also', 'iri', 'Related resource'),
  term('rdfs:isDefinedBy', 'Is defined by', 'iri', 'Defining resource'),

  term('owl:versionInfo', 'Version info', 'plain', 'Version string'),
  term('owl:deprecated', 'Deprecated', 'plain', 'true / false'),
  term('owl:priorVersion', 'Prior version', 'iri', 'Previous version IRI'),
  term('owl:incompatibleWith', 'Incompatible with', 'iri', 'Incompatible version IRI'),

  term('dcterms:title', 'Title', 'text', 'Formal title'),
  term('dcterms:description', 'Description', 'text', 'Longer description'),
  term('dcterms:creator', 'Creator', 'text', 'Person or organisation'),
  term('dcterms:contributor', 'Contributor', 'text', 'Additional contributor'),
  term('dcterms:publisher', 'Publisher', 'text', 'Publishing body'),
  term('dcterms:created', 'Created', 'date', 'YYYY-MM-DD'),
  term('dcterms:modified', 'Modified', 'date', 'YYYY-MM-DD'),
  term('dcterms:license', 'License', 'iri', 'License IRI'),
  term('dcterms:rights', 'Rights', 'text', 'Rights statement'),
  term('dcterms:source', 'Source', 'iri', 'Source resource'),

  term('skos:prefLabel', 'Preferred label', 'text', 'Preferred term'),
  term('skos:altLabel', 'Alternative label', 'text', 'Synonym or variant'),
  term('skos:hiddenLabel', 'Hidden label', 'text', 'Misspelling, search alias'),
  term('skos:definition', 'Definition', 'text', 'Formal definition'),
  term('skos:scopeNote', 'Scope note', 'text', 'Guidance on intended use'),
  term('skos:note', 'Note', 'text', 'General note'),
  term('skos:example', 'Example', 'text', 'Illustrative example'),
  term('skos:editorialNote', 'Editorial note', 'text', 'Note for editors'),

  term('prov:wasDerivedFrom', 'Was derived from', 'iri', 'Source entity IRI'),
  term('prov:wasAttributedTo', 'Was attributed to', 'iri', 'Responsible agent IRI'),
  term('prov:wasGeneratedBy', 'Was generated by', 'iri', 'Generating activity IRI'),
  term('prov:generatedAtTime', 'Generated at time', 'date', 'YYYY-MM-DD'),

  term('vann:preferredNamespacePrefix', 'Preferred prefix', 'plain', 'Suggested prefix'),
  term('vann:preferredNamespaceUri', 'Preferred namespace', 'iri', 'Namespace IRI'),
];

const TERMS_BY_CURIE = new Map(ANNOTATION_TERMS.map((t) => [t.curie, t]));

export function findAnnotationTerm(curie: string): AnnotationTerm | undefined {
  return TERMS_BY_CURIE.get(curie);
}

export function annotationTermIri(curie: string): string | null {
  return expandCurie(curie);
}

/** Prefixes in the order the term picker groups them. */
export const ANNOTATION_PREFIX_ORDER: readonly KnownPrefix[] = [
  'rdfs',
  'skos',
  'dcterms',
  'owl',
  'prov',
  'vann',
];

/** Terms that make sense on the ontology header itself. */
export const ONTOLOGY_ANNOTATION_TERMS: readonly AnnotationTerm[] = ANNOTATION_TERMS.filter((t) =>
  [
    'dcterms:title',
    'dcterms:description',
    'dcterms:creator',
    'dcterms:contributor',
    'dcterms:publisher',
    'dcterms:created',
    'dcterms:modified',
    'dcterms:license',
    'dcterms:rights',
    'owl:versionInfo',
    'owl:priorVersion',
    'rdfs:label',
    'rdfs:comment',
    'rdfs:seeAlso',
    'vann:preferredNamespacePrefix',
    'vann:preferredNamespaceUri',
  ].includes(t.curie),
);

export { NAMESPACES };
